// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZyO52R7hKavOwfXVbs-5jTxbnTBCthI',
    appId: '1:65979519545:web:19d66ec895e4f6b086f3e8',
    messagingSenderId: '65979519545',
    projectId: 'echoes-5f03f',
    authDomain: 'echoes-5f03f.firebaseapp.com',
    storageBucket: 'echoes-5f03f.appspot.com',
    measurementId: 'G-HD6VSNF55K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-CTNy1bngi7iwd9sEUrvnb2_MyaOL05I',
    appId: '1:65979519545:android:ef1d0a07e5fdef6286f3e8',
    messagingSenderId: '65979519545',
    projectId: 'echoes-5f03f',
    storageBucket: 'echoes-5f03f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoNXh9aediEBlSYh5oA3QWp8rusraPDfQ',
    appId: '1:65979519545:ios:3fcf77dbb25cbef886f3e8',
    messagingSenderId: '65979519545',
    projectId: 'echoes-5f03f',
    storageBucket: 'echoes-5f03f.appspot.com',
    iosBundleId: 'com.example.echoesOfEquality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoNXh9aediEBlSYh5oA3QWp8rusraPDfQ',
    appId: '1:65979519545:ios:5adb9f6013d2d99686f3e8',
    messagingSenderId: '65979519545',
    projectId: 'echoes-5f03f',
    storageBucket: 'echoes-5f03f.appspot.com',
    iosBundleId: 'com.example.echoesOfEquality.RunnerTests',
  );
}
